name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkou Repository
          uses: actions/checkout@v4
            
        - name: Welcome Messsage
          run: echo "My first GitHub Actions Job"

        - name: List files
          run: ls

        - name: Read File
          run: cat README.md
        
